"""update creator table

Revision ID: c343b8fd97e8
Revises: 924bab6600c3
Create Date: 2024-09-10 18:21:11.749487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c343b8fd97e8'
down_revision = '924bab6600c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('creators_title_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('creators_title_key', ['title'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
